route:
    receiver: 'slack'

receivers:
    - name: 'slack'
      slack_configs:
          - send_resolved: true
            text: "{{ .CommonAnnotations.description }}"
            username: 'Prometheus'
            channel: '#alertstest'
            api_url: 'https://hooks.slack.com/services/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'
