# config file version
apiVersion: 1

# List of rule groups to import or update
groups:
  - name: hardware
    folder: Qumulo
    interval: 60s
    rules:
      - uid: Ut0U6HH4k
        title: Node time isn't synchonizing
        condition: time_was_not_synchronized
        data:
          - refId: time_is_not_synchronized
            queryType: ''
            relativeTimeRange:
              from: 600
              to: 0
            datasourceUid: PBFA97CFB590B2093
            model:
              editorMode: builder
              expr: qumulo_time_is_not_synchronizing
              hide: false
              intervalMs: 1000
              legendFormat: __auto
              maxDataPoints: 43200
              range: true
              refId: time_is_not_synchronized
          - refId: time_was_not_synchronized
            queryType: ''
            relativeTimeRange:
              from: 0
              to: 0
            datasourceUid: '-100'
            model:
              datasource:
                type: __expr__
                uid: '-100'
              expression: time_is_not_synchronized
              hide: false
              intervalMs: 1000
              maxDataPoints: 43200
              reducer: max
              refId: time_was_not_synchronized
              type: reduce
        noDataState: NoData
        execErrState: Error
        for: 1h
        annotations:
          description: >-
            The time on node {{ $labels.node_id }} isn't synchronizing with a time server.
            Because this eventually causes a time drift, we recommend verifying your node's
            ability to communicate with the time server.
        labels:
          severity: warning
