groups:
- name: qumulo
  rules:
  - alert: qumulo_disk_unhealthy
    expr: qumulo_disk_is_unhealthy == 1
    for: 60s
    labels:
      severity: critical
    annotations:
      summary: "Disk(s) on qumulo system in marked unhealthy"
      description: "{{ $labels.disk_type }} Disk in Node with ID {{ $labels.node_id }} and drive bay {{ $labels.drive_bay }} on qumulo cluster instance {{ $labels.instance }} is marked unhealthy."

  - alert: missing_nfs_calls
    expr: absent(qumulo_protocol_operations_total{protocol="nfs"})
    for: 2m
    labels:
      severity: critical
    annotations:
      summary: "No NFS operations against qumulo cluster"
      description: "Missing NFS protocol operations on qumulo cluster instance {{ $labels.instance }}."

  - alert: missing_smb_calls
    expr: absent(qumulo_protocol_operations_total{protocol="smb"})
    for: 2m
    labels:
      severity: critical
    annotations:
      summary: "No SMB operations against qumulo cluster"
      description: "Missing SMB protocol operations on qumulo cluster instance {{ $labels.instance }}."
