groups:
- name: qumulo
  rules:
  - alert: qumulo_disk_unhealthy
    expr: qumulo_disk_is_unhealthy
    for: 60s
    labels:
      severity: critical
    annotations:
      summary: "Disk(s) on qumulo system in marked unhealthy"
      description: "{{ $labels.disk_type }} Disk in Node with ID {{ $labels.node_id }} and drive bay {{ $labels.drive_bay }} on qumulo cluster instance {{ $labels.instance }} is marked unhealthy."

  - alert: missing_nfs_calls
    expr: absent(qumulo_protocol_operations_total{protocol="nfs"})
    for: 2m
    labels:
      severity: critical
    annotations:
      summary: "No NFS operations against qumulo cluster"
      description: "Missing NFS protocol operations on qumulo cluster instance {{ $labels.instance }}."

  - alert: missing_smb_calls
    expr: absent(qumulo_protocol_operations_total{protocol="smb"})
    for: 2m
    labels:
      severity: critical
    annotations:
      summary: "No SMB operations against qumulo cluster"
      description: "Missing SMB protocol operations on qumulo cluster instance {{ $labels.instance }}."

- name: targets
  rules:
  - alert: monitor_service_down
    expr: up == 0
    for: 30s
    labels:
      severity: critical
    annotations:
      summary: "Monitor service non-operational"
      description: "Service {{ $labels.instance }} is down."

- name: host
  rules:
  - alert: high_cpu_load
    expr: node_load1 > 1.5
    for: 30s
    labels:
      severity: warning
    annotations:
      summary: "Server under high load"
      description: "Docker host is under high load, the avg load 1m is at {{ $value}}. Reported by instance {{ $labels.instance }} of job {{ $labels.job }}."

  - alert: high_memory_load
    expr: (sum(node_memory_MemTotal_bytes) - sum(node_memory_MemFree_bytes + node_memory_Buffers_bytes + node_memory_Cached_bytes) ) / sum(node_memory_MemTotal_bytes) * 100 > 85
    for: 30s
    labels:
      severity: warning
    annotations:
      summary: "Server memory is almost full"
      description: "Docker host memory usage is {{ humanize $value}}%. Reported by instance {{ $labels.instance }} of job {{ $labels.job }}."

  - alert: high_storage_load
    expr: (node_filesystem_size_bytes{fstype="aufs"} - node_filesystem_free_bytes{fstype="aufs"}) / node_filesystem_size_bytes{fstype="aufs"}  * 100 > 85
    for: 30s
    labels:
      severity: warning
    annotations:
      summary: "Server storage is almost full"
      description: "Docker host storage usage is {{ humanize $value}}%. Reported by instance {{ $labels.instance }} of job {{ $labels.job }}."

- name: containers
  rules:
  - alert: grafana_down
    expr: absent(container_memory_usage_bytes{name="grafana"})
    for: 30s
    labels:
      severity: critical
    annotations:
      summary: "Grafana down"
      description: "Grafana container is down for more than 30 seconds."

  - alert: grafana_high_cpu
    expr: sum(rate(container_cpu_usage_seconds_total{name="grafana"}[1m])) / count(node_cpu_seconds_total{mode="system"}) * 100 > 10
    for: 30s
    labels:
      severity: warning
    annotations:
      summary: "Grafana high CPU usage"
      description: "Grafana CPU usage is {{ humanize $value}}%."

  - alert: grafana_high_memory
    expr: sum(container_memory_usage_bytes{name="grafana"}) > 1200000000
    for: 30s
    labels:
      severity: warning
    annotations:
      summary: "Grafana high memory usage"
      description: "Grafana memory consumption is at {{ humanize $value}}."

