{
 "title": "Cluster Overview",
 "tags": [ "qumulo" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "busy_ops",
    "query": {
     "query": "query_result(topk(10, avg_over_time(qumulo_protocol_operations_total[${__range_s}s])))"
    }
   },
   { "name": "cluster", "query": { "query": "qumulo_fs_capacity_bytes" } }
  ]
 },
 "panels": [
  {
   "title": "Cluster Info",
   "type": "table",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "last_over_time(qumulo_info{instance=~\"$cluster\"}[24h])",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Capacity", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "Capacity",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "qumulo_fs_free_bytes{instance=~\"$cluster\"}",
     "legendFormat": "free"
    },
    {
     "expr": "qumulo_fs_directory_used_bytes{instance=~\"$cluster\"}",
     "legendFormat": "{{usage_type}}"
    }
   ]
  },
  {
   "title": "Capacity Trends",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 5, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "qumulo_fs_directory_used_bytes{instance=~\"$cluster\"}",
     "legendFormat": "{{usage_type}}"
    },
    {
     "expr": "qumulo_fs_free_bytes{instance=~\"$cluster\"}",
     "legendFormat": "free"
    },
    {
     "expr": "qumulo_fs_capacity_bytes{instance=~\"$cluster\"}",
     "legendFormat": "capacity"
    }
   ]
  },
  {
   "title": "Data Types",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 4, "x": 11, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "qumulo_fs_directory_tree_entries{instance=~\"$cluster\"}",
     "legendFormat": "{{entry_type}}"
    }
   ]
  },
  {
   "title": "Snapshot Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 15, "y": 4 },
   "targets": [
    {
     "expr": "qumulo_fs_snapshots{instance=~\"$cluster\"}",
     "legendFormat": "Snapshots"
    }
   ]
  },
  { "title": "Performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by(io_type) (rate(qumulo_protocol_operation_bytes_total{instance=~\"$cluster\"}[$__rate_interval]))",
     "legendFormat": "{{io_type}}"
    }
   ]
  },
  {
   "title": "IOPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "sum(rate(qumulo_protocol_operations_total{instance=~\"$cluster\", io_type=\"read\"}[$__rate_interval]))",
     "legendFormat": "read"
    },
    {
     "expr": "sum(rate(qumulo_protocol_operations_total{instance=~\"$cluster\", io_type=\"write\"}[$__rate_interval]))",
     "legendFormat": "write"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 14, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by(protocol, io_type, data_type) (rate(qumulo_protocol_operation_latency_seconds_sum{instance=~\"$cluster\"}[$__rate_interval])) / sum by(protocol, io_type, data_type) (rate(qumulo_protocol_operation_latency_seconds_count{instance=~\"$cluster\"}[$__rate_interval]))",
     "legendFormat": "{{protocol}} {{data_type}} {{io_type}}"
    }
   ]
  },
  {
   "title": "Active Client Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "qumulo_protocol_client_connections_total{instance=~\"$cluster\"} - qumulo_protocol_client_disconnections_total{instance=~\"$cluster\"}",
     "legendFormat": "{{protocol}}"
    }
   ]
  },
  {
   "title": "Top Protocol Ops",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "rate(qumulo_protocol_operations_total{op_name=~\"$busy_ops\", instance=~\"$cluster\"}[$__rate_interval])",
     "legendFormat": "{{op_name}}"
    }
   ]
  },
  {
   "title": "Top Protocol Ops Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 14, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(qumulo_protocol_operation_latency_seconds_sum{op_name=~\"$busy_ops\", instance=\"$cluster\"}[$__rate_interval]) / rate(qumulo_protocol_operation_latency_seconds_count{op_name=~\"$busy_ops\", instance=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "{{op_name}}"
    }
   ]
  },
  { "title": "AD/LDAP", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "AD Netlogon Request Throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(qumulo_ad_netlogon_requests_total{instance=~\"$cluster\"}[$__rate_interval])",
     "legendFormat": "{{server_url}}"
    }
   ]
  },
  {
   "title": "AD Netlogon Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(qumulo_ad_netlogon_request_errors_total{instance=~\"$cluster\"}[$__rate_interval])",
     "legendFormat": "{{server_url}}"
    }
   ]
  },
  {
   "title": "AD Netlogon Request Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 14, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(qumulo_ad_netlogon_request_latency_seconds_sum{instance=~\"$cluster\"}[$__rate_interval]) / rate(qumulo_ad_netlogon_request_latency_seconds_count{instance=~\"$cluster\"}[$__rate_interval])",
     "legendFormat": "{{server_url}}"
    }
   ]
  },
  {
   "title": "LDAP Operation Throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(qumulo_ldap_operations_total{instance=~\"$cluster\"}[$__rate_interval])",
     "legendFormat": "{{domain_url}}"
    }
   ]
  },
  {
   "title": "LDAP Operation Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(qumulo_ldap_operation_errors_total{instance=~\"$cluster\"}[$__rate_interval])",
     "legendFormat": "{{domain_url}}"
    }
   ]
  },
  {
   "title": "LDAP Operation Referrals",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 14, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(qumulo_ldap_operation_referrals_total{instance=~\"$cluster\"}[$__rate_interval])",
     "legendFormat": "{{domain_url}}"
    }
   ]
  },
  {
   "title": "LDAP Request Throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(qumulo_ldap_lookup_requests_total{instance=~\"$cluster\"}[$__rate_interval])",
     "legendFormat": "{{server_url}}"
    }
   ]
  },
  {
   "title": "LDAP Request Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(qumulo_ldap_lookup_request_errors_total{instance=~\"$cluster\"}[$__rate_interval])",
     "legendFormat": "{{server_url}}"
    }
   ]
  },
  {
   "title": "LDAP Request Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 14, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(qumulo_ldap_lookup_request_latency_seconds_sum{instance=~\"$cluster\"}[$__rate_interval]) / rate(qumulo_ldap_lookup_request_latency_seconds_count{instance=~\"$cluster\"}[$__rate_interval])",
     "legendFormat": "{{server_url}}"
    }
   ]
  }
 ]
}