{
 "title": "Node Overview",
 "tags": [ "qumulo" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "cluster", "query": { "query": "qumulo_quorum_node_is_offline" } },
   {
    "name": "nodes",
    "query": {
     "query": "qumulo_quorum_node_is_offline{instance=~\\\"$cluster\\\"}"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Cluster Info",
   "type": "table",
   "gridPos": { "h": 3, "w": 13, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "qumulo_info{instance=~\"$cluster\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Time Synchronized",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 13, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(qumulo_time_is_not_synchronizing{instance=~\"$cluster\", node_id=~\"$nodes\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Node Info",
   "type": "table",
   "gridPos": { "h": 6, "w": 20, "x": 0, "y": 3 },
   "targets": [
    {
     "expr": "qumulo_node_info{instance=~\"$cluster\"}",
     "legendFormat": "{{node_model}}"
    },
    {
     "expr": "qumulo_quorum_node_is_offline{instance=~\"$cluster\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "qumulo_cpu_temperature_celsius{instance=~\"$cluster\", node_id=~\"$nodes\"}",
     "legendFormat": "node {{node_id}} cpu {{cpu}}"
    },
    {
     "expr": "min(qumulo_cpu_max_temperature_celsius{instance=~\"$cluster\", node_id=~\"$nodes\"})",
     "legendFormat": "max temperature"
    }
   ]
  },
  {
   "title": "Fan Speed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 10, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "rotrpm" } },
   "targets": [
    {
     "expr": "qumulo_fan_speed_rpm{instance=~\"$cluster\", node_id=~\"$nodes\"}",
     "legendFormat": "node {{node_id}} {{fan}}"
    }
   ]
  },
  {
   "title": "Memory Correctable ECC Errors",
   "type": "stat",
   "gridPos": { "h": 5, "w": 20, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "qumulo_memory_correctable_ecc_errors_total{instance=~\"$cluster\", node_id=~\"$nodes\"}",
     "legendFormat": "node {{node_id}}"
    }
   ]
  },
  {
   "title": "Power Supplies",
   "type": "stat",
   "gridPos": { "h": 5, "w": 20, "x": 0, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "qumulo_power_supply_is_unhealthy{instance=~\"$cluster\", node_id=~\"$nodes\"}",
     "legendFormat": "node {{node_id}} {{location}}"
    }
   ]
  },
  {
   "title": "Disks",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "collapsed": true,
   "panels": [
    {
     "title": "Disk Status",
     "type": "stat",
     "gridPos": { "h": 7, "w": 20, "x": 0, "y": 30 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "qumulo_disk_is_unhealthy{instance=~\"$cluster\", node_id=~\"$nodes\"}",
       "legendFormat": "node {{node_id}} bay {{drive_bay}}"
      }
     ]
    },
    {
     "title": "Disk Latencies",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 20, "x": 0, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(qumulo_disk_operation_latency_seconds_sum{instance=~\"$cluster\", node_id=~\"$nodes\"}[$__rate_interval]) / rate(qumulo_disk_operation_latency_seconds_count{instance=~\"$cluster\"}[$__rate_interval])",
       "legendFormat": "Node {{node_id}} bay {{drive_bay}} ({{disk_type}})"
      }
     ]
    },
    {
     "title": "Disk Endurance",
     "type": "gauge",
     "gridPos": { "h": 7, "w": 20, "x": 0, "y": 45 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "qumulo_disk_endurance_percent{instance=~\"$cluster\"}",
       "legendFormat": "node {{node_id}} bay {{drive_bay}}"
      }
     ]
    },
    {
     "title": "Uncorrectable Media Errors",
     "type": "timeseries",
     "description": "Uncorrectable media errors are failures to read or write to the physical disk that could not be resolved using error correction technology. These errors can lead to reallocating sectors. Large or rapidly increasing numbers of media errors may be an indicator that a drive will fail, especially on HDDs.",
     "gridPos": { "h": 8, "w": 10, "x": 0, "y": 52 },
     "targets": [
      {
       "expr": "qumulo_disk_uncorrectable_media_errors_total{instance=~\"$cluster\", node_id=~\"$nodes\"}",
       "legendFormat": "Node {{node_id}} bay {{drive_bay}} ({{disk_type}})"
      }
     ]
    },
    {
     "title": "Transport Errors",
     "type": "timeseries",
     "description": "Transport errors are failures to send or receive data between the drive controller and the disk. Large or rapidly increasing numbers of transport errors may be an indicator that the disk needs to be reseated, the transport cable needs to be replaced, the disk may needs to be replaced, or the drive controller needs to be replaced.",
     "gridPos": { "h": 8, "w": 10, "x": 10, "y": 52 },
     "targets": [
      {
       "expr": "qumulo_disk_transport_errors_total{instance=~\"$cluster\", node_id=~\"$nodes\"}",
       "legendFormat": "Node {{node_id}} bay {{drive_bay}} ({{disk_type}})"
      }
     ]
    }
   ]
  },
  {
   "title": "Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "collapsed": true,
   "panels": [
    {
     "title": "Network Health",
     "type": "stat",
     "gridPos": { "h": 5, "w": 20, "x": 0, "y": 61 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by(node_id, bond, role) (qumulo_network_interface_is_down{instance=~\"$cluster\", node_id=~\"$nodes\"})",
       "legendFormat": "node{{node_id}} {{role}}"
      }
     ]
    },
    {
     "title": "Network Interface Health",
     "type": "stat",
     "gridPos": { "h": 5, "w": 20, "x": 0, "y": 66 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "qumulo_network_interface_is_down{instance=~\"$cluster\", node_id=~\"$nodes\"}",
       "legendFormat": "node{{node_id}} {{role}} {{interface}}"
      }
     ]
    },
    {
     "title": "Network Link Speed",
     "type": "stat",
     "gridPos": { "h": 5, "w": 20, "x": 0, "y": 71 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "qumulo_network_interface_link_speed_bits_per_second",
       "legendFormat": "node{{node_id}} {{role}} {{interface}}"
      }
     ]
    },
    {
     "title": "Network Throughput",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 7, "x": 0, "y": 76 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "rate(qumulo_network_interface_transmitted_bytes_total{instance=~\"$cluster\", node_id=~\"$nodes\"}[$__rate_interval])",
       "legendFormat": "Transmitted node{{node_id}} {{role}} {{interface}}"
      },
      {
       "expr": "rate(qumulo_network_interface_received_bytes_total{instance=~\"$cluster\", node_id=~\"$nodes\"}[$__rate_interval])",
       "legendFormat": "Received node{{node_id}} {{role}} {{interface}}"
      }
     ]
    },
    {
     "title": "Network Packets",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 7, "x": 7, "y": 76 },
     "targets": [
      {
       "expr": "rate(qumulo_network_interface_transmitted_packets_total{instance=~\"$cluster\", node_id=~\"$nodes\"}[$__rate_interval])",
       "legendFormat": "Transmitted node{{node_id}} {{role}} {{interface}}"
      },
      {
       "expr": "rate(qumulo_network_interface_received_packets_total{instance=~\"$cluster\", node_id=~\"$nodes\"}[$__rate_interval])",
       "legendFormat": "Received node{{node_id}} {{role}} {{interface}}"
      }
     ]
    },
    {
     "title": "Network Errors",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 14, "y": 76 },
     "targets": [
      {
       "expr": "qumulo_network_interface_transmit_errors_total{instance=~\"$cluster\", node_id=~\"$nodes\"}",
       "legendFormat": "Transmit node{{node_id}} {{role}} {{interface}}"
      },
      {
       "expr": "qumulo_network_interface_receive_errors_total{instance=~\"$cluster\", node_id=~\"$nodes\"}",
       "legendFormat": "Receive node{{node_id}} {{role}} {{interface}}"
      }
     ]
    }
   ]
  }
 ]
}