{
 "title": "Qumulo Node Overview",
 "tags": [ "qumulo" ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "cluster", "query": { "query": "qumulo_quorum_node_is_offline" } },
   { "name": "nodes", "query": { "query": "qumulo_quorum_node_is_offline" } }
  ]
 },
 "panels": [
  {
   "title": "Disk Latencies",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(qumulo_disk_operation_latency_seconds_sum{instance=~\"$cluster\", node_id=~\"$nodes\"}[$__rate_interval]) / rate(qumulo_disk_operation_latency_seconds_count{instance=~\"$cluster\"}[$__rate_interval])",
     "legendFormat": "Node{{node_id}}_{{disk_type}}_bay{{drive_bay}}"
    }
   ]
  },
  {
   "title": "CPU Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "qumulo_cpu_temperature_celsius{instance=~\"$cluster\", node_id=~\"$nodes\"}",
     "legendFormat": "node{{node_id}}_cpu{{cpu}}"
    }
   ]
  },
  {
   "title": "Time Synchronized",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(qumulo_time_is_not_synchronizing{instance=~\"$cluster\", node_id=~\"$nodes\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Correctable ECC Errors",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 3, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "qumulo_memory_correctable_ecc_errors_total{instance=~\"$cluster\", node_id=~\"$nodes\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Fan Speed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "rotrpm" } },
   "targets": [
    {
     "expr": "qumulo_fan_speed_rpm{instance=~\"$cluster\", node_id=~\"$nodes\"}",
     "legendFormat": "node{{node_id}} {{fan}}"
    }
   ]
  }
 ]
}