{
 "title": "Qumulo Cluster Overview",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "busy_ops",
    "query": {
     "query": "query_result(topk(10, avg_over_time(qumulo_protocol_operations_total[${__range_s}s])))"
    }
   },
   { "name": "cluster", "query": { "query": "qumulo_quorum_node_is_offline" } }
  ]
 },
 "panels": [
  {
   "title": "Cluster Name",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "qumulo_info", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Version",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "qumulo_info", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "UUID",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 10, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "qumulo_info", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Capacity",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "qumulo_fs_free_bytes{instance=~\"$cluster\"}",
     "legendFormat": "free"
    },
    {
     "expr": "qumulo_fs_directory_used_bytes{instance=~\"$cluster\"}",
     "legendFormat": "{{usage_type}}"
    }
   ]
  },
  {
   "title": "Capacity Trends",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 5, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "qumulo_fs_directory_used_bytes{instance=~\"$cluster\"}",
     "legendFormat": "{{usage_type}}"
    },
    {
     "expr": "qumulo_fs_free_bytes{instance=~\"$cluster\"}",
     "legendFormat": "free"
    }
   ]
  },
  {
   "title": "Data Types",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 5, "x": 11, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "qumulo_fs_directory_tree_entries{instance=~\"$cluster\"}",
     "legendFormat": "{{entry_type}}"
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by(io_type) (rate(qumulo_protocol_operation_bytes_total{instance=~\"$cluster\"}[1m]))",
     "legendFormat": "{{io_type}}"
    }
   ]
  },
  {
   "title": "Active Client Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 11, "y": 14 },
   "targets": [
    {
     "expr": "qumulo_protocol_client_connections_total{instance=~\"$cluster\"} - qumulo_protocol_client_disconnections_total{instance=~\"$cluster\"}",
     "legendFormat": "{{protocol}}"
    }
   ]
  },
  {
   "title": "Top Protocol Ops",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "rate(qumulo_protocol_operations_total{op_name=~\"$busy_ops\", instance=~\"$cluster\"}[$__rate_interval])",
     "legendFormat": "{{op_name}}"
    }
   ]
  },
  {
   "title": "IOPS",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 11, "x": 11, "y": 22 },
   "targets": [
    {
     "expr": "sum(rate(qumulo_protocol_operations_total{instance=~\"$cluster\", io_type=\"read\"}[$__rate_interval]))",
     "legendFormat": "read"
    },
    {
     "expr": "sum(rate(qumulo_protocol_operations_total{instance=~\"$cluster\", io_type=\"write\"}[$__rate_interval]))",
     "legendFormat": "write"
    }
   ]
  },
  {
   "title": "Top Protocol Ops Latency",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 11, "x": 11, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(qumulo_protocol_operation_latency_seconds_sum{op_name=~\"$busy_ops\", instance=\"$cluster\"}[$__rate_interval]) / rate(qumulo_protocol_operation_latency_seconds_count{op_name=~\"$busy_ops\", instance=\"$cluster\"}[$__rate_interval])",
     "legendFormat": "{{op_name}}"
    }
   ]
  },
  {
   "title": "Node Statuses",
   "type": "stat",
   "gridPos": { "h": 3, "w": 22, "x": 0, "y": 35 },
   "repeat": "Cluster",
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "qumulo_quorum_node_is_offline{instance=~\"$cluster\"}",
     "legendFormat": "Node - {{node_id}}"
    }
   ]
  },
  {
   "title": "LDAP Request Errors",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(qumulo_ldap_lookup_request_errors_total{instance=~\"$cluster\"}[1m])",
     "legendFormat": "{{server_url}}"
    }
   ]
  },
  {
   "title": "LDAP Request Throughput",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 8, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(qumulo_ldap_lookup_requests_total{instance=~\"$cluster\"}[1m])",
     "legendFormat": "{{server_url}}"
    }
   ]
  },
  {
   "title": "LDAP Request Latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 15, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(qumulo_ldap_lookup_request_latency_seconds_sum{instance=~\"$cluster\"}[$__rate_interval]) / rate(qumulo_ldap_lookup_request_latency_seconds_count{instance=~\"$cluster\"}[$__rate_interval])",
     "legendFormat": "{{server_url}}"
    }
   ]
  }
 ]
}